apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpserver
  namespace: voting
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: httpserver
  namespaceSelector:
    matchNames: ["voting"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpcserver
  namespace: voting
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: grpcserver
  namespaceSelector:
    matchNames: ["voting"]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: voting
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames: ["voting"]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s

