apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver
  namespace: vote-system
spec:
  rules:
    - host: vote.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpserver
                port:
                  number: 8080

